language: go
go:
  - 1.3
  - release
  - tip

install:
  - go get -v ./...
  - go get github.com/codegangsta/inject
  - go get github.com/codegangsta/martini
  - go get github.com/codegangsta/martini-contrib/render
  - go get github.com/garyburd/redigo/redis
  - go get github.com/go-martini/martini
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - export PATH=$PATH:$HOME/gopath/bin

script: go test -v ./...