language: go
go:
- 1.3
- release
- tip
before_install:
- go get -v ./...
- go get github.com/tools/godep
script:
- godep get
- godep save
- export PATH=$PATH:$HOME/gopath/bin
- godep go test -v ./...
deploy:
  provider: heroku
# deploy方法指定
  strategy: git
  api_key:
    secure: HSFfe9ToHPXWTGFvd3peOQEumEMDpgCad7sxaUBiAqcRcBu69Xn5C/xH2ekafXy/KVnYlrEDP77/jt5tFhlZvCaRe6fDkaa2CqRyXI2i4b8AZz+HEMUmfAATthKSqVgamOy4fF9VfNquZxmihXW1e1YwVju+eL1NL3qw4xZGzxM=
  app: martini-sample
  on:
    repo: shinofara/martini-sample
