language: go
go:
  - 1.3
  - release
  - tip

before_install:
  - go get -v ./...
  - go get github.com/tools/godep

script:
  - godep get
  - godep save
  - export PATH=$PATH:$HOME/gopath/bin
  - godep go test -v ./...

