language: go
go:
- 1.3
- release
before_install:
- go get -v ./...
- go get github.com/tools/godep
script:
- GOPATH=`godep path`:$GOPATH
- export PATH=$PATH:$HOME/gopath/bin
- go install
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: a21CPWi4d47yEqBUjJpPR5u71rN/0+6PkvxZIGm+DDa8ifx04Xi61WCDpyr2xegr6Lg8Q0W0xbVDJh1N+4/JaIT4rYvFbazBDsteXOUhKg/rzTYJyCGJQBioXhpN6JtcZCjzP5MxV2V4oVSrvANa1XUszk8WK3I4Go9W8iDR+gQ=
  app: martini-sample
  on:
    repo: shinofara/martini-sample
HEROKU_API_KEY=eaa76f06b4a9e7dcf3063a0568bafa2e27baca32:
  secure: iS/SSCYI//Am1g93l5Kf00q1OPxi6utVPidduGZreA65YKHV9Xa3CfiX+kkmS7lQKSMks4M+vRQ87xkFeYHVWsypVy3PEXxppuQ/+ytHrBNMwrjQtUdyCF7tc7wQiM0vOM9ySYg1IrMtKgwQ7HjqoJ9cZTtYxTrcmxR8p5TqplE=
