language: go
go:
- 1.3
- release
before_install:
- go get -v ./...
- go get github.com/tools/godep
script:
- GOPATH=`godep path`:$GOPATH
- export PATH=$PATH:$HOME/gopath/bin
- go install
deploy:
  provider: heroku
  api_key:
    secure: jz+BFW/DCZM9VpNEwNT8UXcDikKEw7QezHx1zbIWl20tNBHFYpL13Xh8yVbI2OIKF/NCGGQ6moXwL3CZzZ0/lMIZyM3YbNyWEVuQvcIL3HORNnB0L5PEolyxFm5J74iJhLEitgAO1VCfgyZ/BVRZz6dsZudYU80qKvMvdHDRIe0=
  app: martini-sample
  on:
    repo: shinofara/martini-sample
