language: go
go:
  - 1.3
  - release
  - tip

install:
  - go get -v ./...
  - go get github.com/tools/godep
  - export PATH=$PATH:$HOME/gopath/bin
  - godep get
  - godep save
script: godep go test -v ./...

