language: go
go:
    - 1.3

install:
  - go get -v ./...
  - go get github.com/codegangsta/inject
  - go get github.com/codegangsta/martini
  - go get github.com/codegangsta/martini-contrib/render
  - go get github.com/garyburd/redigo/redis
  - go get github.com/go-martini/martini
  - export PATH=$PATH:$HOME/gopath/bin

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --failOnPending --randomizeSuites --race
